const antiSexualHarassmentCode = [
  {
    policy_id: "POL-ASH-001",
    title: "Light Offenses – Forms of Sexual Harassment",
    source: "Anti Sexual Harassment Code",
    section: "Light Offense",
    content: "Surreptitious looking or stealing a look at a person's private parts or underclothing; malicious leering or ogling; sexual flirtation or persistent unwanted attention with sexual overtones; inquiries or comments about a person's sex life and gender orientation; communicating sexist/smutty remarks causing discomfort, embarrassment, offense, or insult; display of sexually-offensive pictures, materials, or graffiti; and other analogous cases.",
    punishment: null,
    keywords: ["light offense", "leering", "sexist remarks", "offensive materials", "unwanted attention"],
    applicable_to: ["employees", "students"],
    category: "sexual_harassment_classification",
    relevance_score: 0.95
  },
  {
    policy_id: "POL-ASH-002",
    title: "Less Grave Offenses – Forms of Sexual Harassment",
    source: "Anti Sexual Harassment Code",
    section: "Less Grave Offense",
    content: "Verbal and/or non-verbal abuse with sexual overtones, including offensive hand or body gestures; derogatory or degrading remarks or innuendoes directed toward the opposite or one's sex, sexual orientation or gender identity; touching or brushing against a victim's body; pinching that does not fall under grave offenses; sexual advances or propositions; and other analogous cases.",
    punishment: null,
    keywords: ["less grave offense", "verbal abuse", "touching", "sexual advances", "derogatory remarks"],
    applicable_to: ["employees", "students"],
    category: "sexual_harassment_classification",
    relevance_score: 0.95
  },
  {
    policy_id: "POL-ASH-003",
    title: "Grave Offenses – Forms of Sexual Harassment",
    source: "Anti Sexual Harassment Code",
    section: "Grave Offense",
    content: "Touching or groping of private parts of the body; forced kissing; requesting sexual favor in exchange for employment, promotion, a passing grade, the granting of honors or scholarship; attempted or consummated unwanted sexual intercourse or torture of the person in a sexual manner; and other analogous cases.",
    punishment: null,
    keywords: ["grave offense", "groping", "forced kissing", "sexual favor", "sexual intercourse"],
    applicable_to: ["employees", "students"],
    category: "sexual_harassment_classification",
    relevance_score: 1.0
  },
  {
    policy_id: "POL-ASH-004",
    title: "Penalties for Employees – By Offense Category",
    source: "Anti Sexual Harassment Code",
    section: "Penalties",
    content: "Light Offense – 1st offense: reprimand or suspension 1 month 1 day to 6 months; 2nd offense: fine or suspension 6 months 1 day to 1 year; 3rd offense: dismissal. Less Grave Offense – 1st offense: suspension 6 months 1 day to 1 year; 2nd offense: dismissal. Grave Offense – 1st offense: dismissal.",
    punishment: "As described in content.",
    keywords: ["penalties", "suspension", "dismissal", "employee", "progressive discipline"],
    applicable_to: ["employees"],
    category: "administrative_penalties",
    relevance_score: 0.95
  },
  {
    policy_id: "POL-ASH-005",
    title: "Penalties for Students – By Offense Category",
    source: "Anti Sexual Harassment Code",
    section: "Penalties",
    content: "Light Offense – 1st offense: reprimand or community service not exceeding 30 hours; 2nd offense: suspension not exceeding one semester; 3rd offense: expulsion. Less Grave Offense – 1st offense: community service of 60 hours; 2nd offense: suspension for one year; 3rd offense: expulsion. Grave Offense – 1st offense: suspension for one academic year to expulsion.",
    punishment: "As described in content.",
    keywords: ["penalties", "students", "suspension", "expulsion", "community service"],
    applicable_to: ["students"],
    category: "student_discipline",
    relevance_score: 0.95
  }
];

const irrRA11313 = [
  {
    policy_id: "POL-SSA-001",
    title: "Title and Purpose",
    source: "IRR of RA 11313 (Safe Spaces Act)",
    section: "Rule I, Secs. 1‑2",
    content: "These rules shall be known and cited as the Implementing Rules and Regulations (IRR) of Republic Act No. 11313, otherwise known as the 'Safe Spaces Act'. They are promulgated to provide guidelines and mechanisms in the implementation of the Safe Spaces Act.",
    punishment: null,
    keywords: ["title", "purpose", "IRR", "safe spaces act"],
    applicable_to: ["implementing agencies"],
    category: "general_provisions",
    relevance_score: 0.5
  },
  {
    policy_id: "POL-SSA-002",
    title: "Declaration of Policies",
    source: "IRR of RA 11313 (Safe Spaces Act)",
    section: "Rule I, Sec. 3",
    content: "It is the policy of the State to value the dignity of every human person and guarantee full respect for human rights. It is likewise the policy of the State to recognize the role of women in nation-building and ensure the fundamental equality before the law of women and men. The State also recognizes that both men and women must have equality, security, and safety not only in private but also on the streets, public spaces, online, workplaces and educational and training institutions.",
    punishment: null,
    keywords: ["policy", "dignity", "human rights", "equality", "safety"],
    applicable_to: ["state", "all persons"],
    category: "general_provisions",
    relevance_score: 0.6
  },
  {
    policy_id: "POL-SSA-003",
    title: "Definitions – Key Terms",
    source: "IRR of RA 11313 (Safe Spaces Act)",
    section: "Rule II, Sec. 4",
    content: "Defines terms: Catcalling – unwanted remarks, wolf-whistling, misogynistic/transphobic/homophobic/sexist slurs; Common carriers; Cyberstalking; Employee; Employer; Gender; Gender-based online sexual harassment; Gender identity and/or expression; Homophobic remarks or slurs; Information and communication system; Misogynistic remarks or slurs; Public spaces; Sexist remarks or slurs; Transphobic remarks or slurs; Stalking.",
    punishment: null,
    keywords: ["definitions", "catcalling", "cyberstalking", "gender identity", "public spaces"],
    applicable_to: ["all persons"],
    category: "definitions",
    relevance_score: 0.8
  },
  {
    policy_id: "POL-SSA-004",
    title: "Gender‑Based Streets and Public Spaces Sexual Harassment – Definition",
    source: "IRR of RA 11313 (Safe Spaces Act)",
    section: "Rule III, Sec. 5",
    content: "The crimes of gender‑based streets and public spaces sexual harassment are committed through any unwanted and uninvited sexual actions or remarks against any person regardless of the motive. This includes: catcalling, wolf-whistling, unwanted invitations, misogynistic/transphobic/homophobic/sexist slurs; persistent uninvited comments on appearance; relentless requests for personal details; statement of sexual comments and suggestions; public masturbation or flashing of private parts, groping, making offensive body gestures; any advances (verbal or physical) that are unwanted and threaten personal space and safety; persistent telling of sexual jokes, use of sexual names; and stalking.",
    punishment: null,
    keywords: ["public spaces", "catcalling", "groping", "stalking", "sexual remarks"],
    applicable_to: ["all persons"],
    category: "safe_spaces_act",
    relevance_score: 1.0
  },
  {
    policy_id: "POL-SSA-005",
    title: "Duties of Management – Privately‑Owned Places Open to the Public",
    source: "IRR of RA 11313 (Safe Spaces Act)",
    section: "Rule III, Sec. 6",
    content: "Management of restaurants, bars, cinemas, malls, buildings and other privately‑owned places open to the public shall adopt a zero tolerance policy. Measures include: installation of clearly visible warning signs against GBSH with anti‑sexual harassment hotline numbers; designation of at least one anti‑sexual harassment officer; provision of assistance to victims (coordination with police, accompanying victim, making CCTV footage available when ordered by court); provision of a safe gender‑sensitive environment to encourage reporting; development of protocols for handling GBSH. Security guards may conduct citizen’s arrest in flagrante delicto.",
    punishment: null,
    keywords: ["private establishments", "zero tolerance", "CCTV", "anti-sexual harassment officer", "citizen's arrest"],
    applicable_to: ["business establishments", "management"],
    category: "employer_duties",
    relevance_score: 0.9
  },
  {
    policy_id: "POL-SSA-006",
    title: "GBSH in Public Utility Vehicles (PUVs)",
    source: "IRR of RA 11313 (Safe Spaces Act)",
    section: "Rule III, Sec. 7",
    content: "In addition to penalties, the LTO may cancel the license of perpetrators, and the LTFRB may suspend or revoke the franchise of transportation operators who commit GBSH acts. GBSH in PUVs where the perpetrator is the driver constitutes a breach of contract of carriage, creating a presumption of negligence on the part of the owner/operator, rendering them solidarily liable. When a case is filed in court and guilt is found, the court may order cancellation of license, or revocation/suspension of franchise.",
    punishment: "LTO license cancellation; LTFRB franchise suspension/revocation; solidary liability.",
    keywords: ["PUV", "LTO", "LTFRB", "license cancellation", "franchise revocation", "solidary liability"],
    applicable_to: ["drivers", "transportation operators"],
    category: "safe_spaces_act",
    relevance_score: 0.85
  },
  {
    policy_id: "POL-SSA-007",
    title: "GBSH in Streets and Public Spaces Committed by Minors",
    source: "IRR of RA 11313 (Safe Spaces Act)",
    section: "Rule III, Sec. 8",
    content: "If the offense is committed by a minor, the DSWD shall take necessary disciplinary measures and diversion program as provided under RA 9344 (Juvenile Justice and Welfare Act). The program shall include age‑appropriate gender sensitivity training and anti‑sexual harassment awareness activities.",
    punishment: "Diversion program under juvenile justice law.",
    keywords: ["minors", "DSWD", "juvenile justice", "diversion", "gender sensitivity"],
    applicable_to: ["minors"],
    category: "safe_spaces_act",
    relevance_score: 0.8
  },
  {
    policy_id: "POL-SSA-008",
    title: "Duties of Local Government Units (LGUs)",
    source: "IRR of RA 11313 (Safe Spaces Act)",
    section: "Rule III, Sec. 9",
    content: "LGUs shall bear primary responsibility in enforcing GBSH provisions. Duties: pass an ordinance localizing the law within 60 days; disseminate law and ordinance; provide measures to prevent GBSH in educational institutions; discourage GBSH and impose fines; establish an anti‑sexual harassment hotline; coordinate with DILG; establish a referral system; provide training on the law for barangay officials, traffic enforcers, etc.; set up Anti‑Sexual Harassment (ASH) desks in all barangay, city and municipal halls (VAW Desks may serve as ASH desks); create a mechanism for handling and documentation of complaints including Katarungang Pambarangay.",
    punishment: null,
    keywords: ["LGU", "ordinance", "ASH desk", "hotline", "referral system", "training"],
    applicable_to: ["local government units"],
    category: "safe_spaces_act",
    relevance_score: 0.9
  },
  {
    policy_id: "POL-SSA-009",
    title: "Role of DILG",
    source: "IRR of RA 11313 (Safe Spaces Act)",
    section: "Rule III, Sec. 10",
    content: "The DILG shall ensure full implementation of RA 11313 by: inspecting LGUs for compliance; conducting and disseminating surveys and studies on best practices; providing capacity‑building and training activities in coordination with PCW, LGA, and DAP; assisting LGUs in localizing the law; developing guidelines and mechanisms for effective implementation, including interface with Katarungang Pambarangay and strengthening of VAW desks.",
    punishment: null,
    keywords: ["DILG", "monitoring", "capacity building", "localization"],
    applicable_to: ["DILG"],
    category: "safe_spaces_act",
    relevance_score: 0.8
  },
  {
    policy_id: "POL-SSA-010",
    title: "Implementing Bodies for GBSH in Streets and Public Spaces",
    source: "IRR of RA 11313 (Safe Spaces Act)",
    section: "Rule III, Sec. 11",
    content: "The MMDA, local PNP units, and the Women and Children Protection Desk (WCPD) of the PNP shall have authority to apprehend perpetrators and enforce the law. The MMDA and PNP shall deputize enforcers as Anti‑Sexual Harassment Enforcers (ASHE) to receive complaints, apprehend perpetrators in flagrante delicto, bring them to the nearest PNP station, and keep a ledger of offenders. The DILG shall ensure ASH desks in barangays, city/municipal halls, and CCTVs in major roads, alleys, and sidewalks. LGUs shall facilitate access to psychological counseling and support services.",
    punishment: null,
    keywords: ["MMDA", "PNP", "ASHE", "ASH desk", "CCTV", "psychological support"],
    applicable_to: ["MMDA", "PNP", "LGUs"],
    category: "safe_spaces_act",
    relevance_score: 0.85
  },
  {
    policy_id: "POL-SSA-011",
    title: "Penalties – First Tier Street/Public Space Harassment",
    source: "IRR of RA 11313 (Safe Spaces Act)",
    section: "Rule III, Sec. 12(a)",
    content: "Acts: cursing, wolf‑whistling, catcalling, leering, intrusive gazing, taunting, unwanted invitations, misogynistic/transphobic/homophobic/sexist slurs, persistent unwanted comments on appearance, relentless requests for personal details, persistent telling of sexual jokes, use of sexual names, and any statement that invades personal space or threatens personal safety.",
    punishment: "First offense: fine of PHP 1,000 and community service of 12 hours including attendance to Gender Sensitivity Seminar. Second offense: arresto menor (6 to 10 days) or fine of PHP 3,000. Third offense: arresto menor (11 to 30 days) and fine of PHP 10,000.",
    keywords: ["penalties", "catcalling", "leering", "slurs", "community service"],
    applicable_to: ["all persons"],
    category: "safe_spaces_act_penalties",
    relevance_score: 0.9
  },
  {
    policy_id: "POL-SSA-012",
    title: "Penalties – Second Tier Street/Public Space Harassment",
    source: "IRR of RA 11313 (Safe Spaces Act)",
    section: "Rule III, Sec. 12(b)",
    content: "Acts: making offensive body gestures, exposing private parts for sexual gratification (flashing of private parts, public masturbation), groping, and similar lewd sexual actions.",
    punishment: "First offense: fine of PHP 10,000 and community service of 12 hours including Gender Sensitivity Seminar. Second offense: arresto menor (11 to 30 days) or fine of PHP 15,000. Third offense: arresto mayor (1 month 1 day to 6 months) and fine of PHP 20,000.",
    keywords: ["penalties", "flashing", "public masturbation", "groping", "lewd actions"],
    applicable_to: ["all persons"],
    category: "safe_spaces_act_penalties",
    relevance_score: 0.9
  },
  {
    policy_id: "POL-SSA-013",
    title: "Penalties – Third Tier Street/Public Space Harassment",
    source: "IRR of RA 11313 (Safe Spaces Act)",
    section: "Rule III, Sec. 12(c)",
    content: "Acts: stalking, or any of the acts in Sec. 12(a) accompanied by touching, pinching, or brushing against the body (including genitalia, breasts, face, buttocks, inner thighs, etc.).",
    punishment: "First offense: arresto menor (11 to 30 days) or fine of PHP 30,000, including attendance in Gender Sensitivity Seminar. Second offense: arresto mayor (1 month 1 day to 6 months) or fine of PHP 50,000. Third offense: arresto mayor (maximum period) or fine of PHP 100,000.",
    keywords: ["penalties", "stalking", "touching", "pinching", "arresto mayor"],
    applicable_to: ["all persons"],
    category: "safe_spaces_act_penalties",
    relevance_score: 0.9
  },
  {
    policy_id: "POL-SSA-014",
    title: "Gender‑Based Online Sexual Harassment – Definition",
    source: "IRR of RA 11313 (Safe Spaces Act)",
    section: "Rule IV, Sec. 13",
    content: "Gender‑based online sexual harassment refers to an online conduct targeted at a particular person that causes or likely to cause mental, emotional or psychological distress, and fear of personal safety. It includes: physical, psychological and emotional threats; unwanted sexual, misogynistic, transphobic, homophobic, and sexist remarks; invasion of privacy through cyberstalking and incessant messaging; uploading/sharing without consent sexual photos, voice or videos; unauthorized recording and sharing of photos, videos or information online; impersonating victims or posting lies to harm reputation; filing false abuse reports to online platforms to silence victims.",
    punishment: null,
    keywords: ["online harassment", "cyberstalking", "non-consensual sharing", "impersonation", "threats"],
    applicable_to: ["all persons"],
    category: "safe_spaces_act",
    relevance_score: 1.0
  },
  {
    policy_id: "POL-SSA-015",
    title: "Implementing Bodies – Gender‑Based Online Sexual Harassment",
    source: "IRR of RA 11313 (Safe Spaces Act)",
    section: "Rule IV, Sec. 14",
    content: "Implementing bodies include PNP Anti‑Cybercrime Group (PNP ACG), DOJ, Cybercrime Investigation and Coordinating Center (CICC), National Telecommunications Commission (NTC), National Privacy Commission (NPC), and others working together to receive complaints, build cases, and monitor enforcement ensuring confidentiality and privacy of victims.",
    punishment: null,
    keywords: ["PNP ACG", "DOJ", "CICC", "NTC", "NPC", "online enforcement"],
    applicable_to: ["law enforcement", "government agencies"],
    category: "safe_spaces_act",
    relevance_score: 0.8
  },
  {
    policy_id: "POL-SSA-016",
    title: "Procedures for Gender‑Based Online Sexual Harassment",
    source: "IRR of RA 11313 (Safe Spaces Act)",
    section: "Rule IV, Sec. 15",
    content: "The DOJ, PNP, and NBI shall develop procedures and protocols for receiving complaints and handling gender‑based online sexual harassment within 150 days from the effectivity of these rules.",
    punishment: null,
    keywords: ["procedures", "protocols", "DOJ", "PNP", "NBI"],
    applicable_to: ["DOJ", "PNP", "NBI"],
    category: "safe_spaces_act",
    relevance_score: 0.7
  },
  {
    policy_id: "POL-SSA-017",
    title: "Penalties – Gender‑Based Online Sexual Harassment",
    source: "IRR of RA 11313 (Safe Spaces Act)",
    section: "Rule IV, Sec. 16",
    content: "Penalties for gender‑based online sexual harassment.",
    punishment: "Prison correccional (medium period) or fines of PHP 100,000 to PHP 500,000 or both, at the court's discretion. For juridical persons, licenses or franchises shall be revoked. Alien perpetrators may face deportation after sentence and fines.",
    keywords: ["penalties", "online harassment", "imprisonment", "fine", "license revocation"],
    applicable_to: ["all persons", "juridical persons"],
    category: "safe_spaces_act_penalties",
    relevance_score: 0.9
  },
  {
    policy_id: "POL-SSA-018",
    title: "Qualified Gender‑Based Sexual Harassment – Higher Penalty",
    source: "IRR of RA 11313 (Safe Spaces Act)",
    section: "Rule V, Sec. 17",
    content: "Penalty next higher in degree applies if: (a) the act takes place in common carriers or PUVs where perpetrator is driver and offended party is passenger; (b) the offended party is minor, senior citizen, PWD, or breastfeeding mother; (c) the offended party has a mental condition impairing consent; (d) the perpetrator is a member of the uniformed services in uniform; (e) the act occurs in a government agency frontline service premises with government employee perpetrator.",
    punishment: "Penalty one degree higher than the penalty for the underlying act.",
    keywords: ["qualified offense", "aggravating circumstances", "higher penalty", "vulnerable victims"],
    applicable_to: ["all persons"],
    category: "safe_spaces_act",
    relevance_score: 0.9
  },
  {
    policy_id: "POL-SSA-019",
    title: "GBSH in the Workplace – Definition (Safe Spaces Act IRR)",
    source: "IRR of RA 11313 (Safe Spaces Act)",
    section: "Rule VI, Sec. 18",
    content: "Gender‑based sexual harassment in the workplace includes unwelcome sexual advances, requests, or acts of sexual nature (verbal, physical, or via ICT) that detrimentally affect employment or education, including harassment creating intimidating or hostile environments. GBSH may occur between peers or subordinates and superiors.",
    punishment: null,
    keywords: ["workplace", "sexual advances", "hostile environment", "peers", "superiors"],
    applicable_to: ["employees", "employers"],
    category: "safe_spaces_act",
    relevance_score: 0.9
  },
  {
    policy_id: "POL-SSA-020",
    title: "Duties of Employers – GBSH in the Workplace (Safe Spaces Act IRR)",
    source: "IRR of RA 11313 (Safe Spaces Act)",
    section: "Rule VI",
    content: "Employers have the duty to prevent and address GBSH. This includes: promulgating rules and regulations in consultation with employees; creating a Committee on Decorum and Investigation (CODI); providing procedures for resolution, settlement, or prosecution; adopting measures to protect complainants; ensuring confidentiality; and imposing administrative sanctions. The IRR elaborates on the composition of CODI in the workplace, investigation procedures, and the responsibilities of employers and employees.",
    punishment: "Employers may be held solidarily liable for damages if informed of acts and no immediate action taken.",
    keywords: ["employer duty", "CODI", "prevention", "investigation", "confidentiality"],
    applicable_to: ["employers", "heads of offices"],
    category: "safe_spaces_act",
    relevance_score: 0.9
  },
  {
    policy_id: "POL-SSA-021",
    title: "GBSH in Educational/Training Institutions – Definition and Duties",
    source: "IRR of RA 11313 (Safe Spaces Act)",
    section: "Rule VII",
    content: "Gender‑based sexual harassment in educational/training institutions is committed by a person with authority, influence, or moral ascendancy over another. Institutions must adopt policies to prevent and address GBSH, create a CODI (with representatives from administration, teaching/non‑teaching staff, and students/trainees), and provide procedures for investigation and sanctions. The CODI handles complaints and may recommend penalties up to expulsion or dismissal.",
    punishment: "Administrative penalties up to expulsion for students or dismissal for employees.",
    keywords: ["education", "training", "CODI", "moral ascendancy", "expulsion"],
    applicable_to: ["educational institutions", "trainers", "students"],
    category: "safe_spaces_act",
    relevance_score: 0.9
  },
  {
    policy_id: "POL-SSA-022",
    title: "Code of Conduct",
    source: "IRR of RA 11313 (Safe Spaces Act)",
    section: "Rule VIII",
    content: "The IRR provides for a Code of Conduct to be adopted by agencies and institutions, outlining proper decorum, reporting mechanisms, and disciplinary measures. It emphasizes the prohibition of retaliatory actions against complainants and the duty to maintain confidentiality.",
    punishment: null,
    keywords: ["code of conduct", "decorum", "reporting", "confidentiality", "retaliation"],
    applicable_to: ["agencies", "institutions"],
    category: "safe_spaces_act",
    relevance_score: 0.7
  },
  {
    policy_id: "POL-SSA-023",
    title: "Oversight Mechanisms",
    source: "IRR of RA 11313 (Safe Spaces Act)",
    section: "Rule IX",
    content: "The IRR establishes oversight mechanisms to ensure compliance, including monitoring by the CSC, DILG, and other agencies. Regular reporting and evaluation of anti‑sexual harassment measures are required.",
    punishment: null,
    keywords: ["oversight", "monitoring", "compliance", "reporting"],
    applicable_to: ["government agencies"],
    category: "safe_spaces_act",
    relevance_score: 0.6
  },
  {
    policy_id: "POL-SSA-024",
    title: "Confidentiality",
    source: "IRR of RA 11313 (Safe Spaces Act)",
    section: "Rule X",
    content: "All proceedings and records related to complaints of GBSH shall be kept confidential to protect the interests of the complainant, the person complained against, and any other person who may report cases. Breach of confidentiality may result in administrative sanctions.",
    punishment: "Administrative sanctions for breach of confidentiality.",
    keywords: ["confidentiality", "privacy", "records", "proceedings"],
    applicable_to: ["all persons involved in proceedings"],
    category: "safe_spaces_act",
    relevance_score: 0.8
  },
  {
    policy_id: "POL-SSA-025",
    title: "Restraining Orders and Psychological Counseling",
    source: "IRR of RA 11313 (Safe Spaces Act)",
    section: "Rule XI",
    content: "The IRR allows for the issuance of restraining orders to protect victims of GBSH. It also mandates that victims be provided access to psychological counseling and support services, in coordination with the DSWD, DOH, and LGUs.",
    punishment: null,
    keywords: ["restraining order", "counseling", "psychological support", "victim assistance"],
    applicable_to: ["victims", "LGUs", "DSWD", "DOH"],
    category: "safe_spaces_act",
    relevance_score: 0.8
  },
  {
    policy_id: "POL-SSA-026",
    title: "Administrative Sanctions",
    source: "IRR of RA 11313 (Safe Spaces Act)",
    section: "Rule XII",
    content: "The IRR provides that administrative sanctions under the CSC rules (RACCS) and other relevant laws shall apply to government employees who commit GBSH. Penalties may include suspension, dismissal, and other disciplinary actions.",
    punishment: "Suspension, dismissal, or other penalties under civil service rules.",
    keywords: ["administrative sanctions", "CSC", "suspension", "dismissal"],
    applicable_to: ["government employees"],
    category: "safe_spaces_act",
    relevance_score: 0.8
  }
];

const ra7877 = [
  {
    policy_id: "POL-RA7877-001",
    title: "RA 7877 – Work, Education or Training‑Related Sexual Harassment Defined",
    source: "RA 7877 (Anti-Sexual Harassment Act of 1995)",
    section: "Sec. 3",
    content: "Work, education or training‑related sexual harassment is committed by an employer, employee, manager, supervisor, agent of the employer, teacher, instructor, professor, coach, trainer, or any other person who, having authority, influence or moral ascendancy over another in a work or training or education environment, demands, requests or otherwise requires any sexual favor from the other, regardless of whether the demand, request or requirement for submission is accepted. In work environment: when sexual favor is condition for hiring/employment/promotion/privileges, or refusal results in adverse employment effects, or creates intimidating/hostile/offensive environment. In education/training: when offender has care/custody/supervision, or sexual favor is condition for passing grade/honors/scholarship/benefits, or creates intimidating/hostile/offensive environment.",
    punishment: null,
    keywords: ["workplace", "education", "moral ascendancy", "sexual favor", "hostile environment"],
    applicable_to: ["employers", "employees", "teachers", "students"],
    category: "anti_sexual_harassment_act",
    relevance_score: 1.0
  },
  {
    policy_id: "POL-RA7877-002",
    title: "RA 7877 – Duty of Employer or Head of Office",
    source: "RA 7877 (Anti-Sexual Harassment Act of 1995)",
    section: "Sec. 4",
    content: "It shall be the duty of the employer or the head of the work‑related, educational or training environment or institution, to prevent or deter the commission of acts of sexual harassment and to provide the procedures for the resolution, settlement or prosecution of acts of sexual harassment. Towards this end, the employer or head of office shall: (a) promulgate appropriate rules and regulations in consultation with and jointly approved by the employees or students or trainees, prescribing the procedure for investigation and administrative sanctions; (b) create a committee on decorum and investigation of cases on sexual harassment.",
    punishment: null,
    keywords: ["employer duty", "CODI", "rules", "prevention"],
    applicable_to: ["employers", "heads of offices", "educational institutions"],
    category: "anti_sexual_harassment_act",
    relevance_score: 0.9
  },
  {
    policy_id: "POL-RA7877-003",
    title: "RA 7877 – Composition of CODI",
    source: "RA 7877 (Anti-Sexual Harassment Act of 1995)",
    section: "Sec. 4(b)",
    content: "In a work‑related environment, the committee shall be composed of at least one representative each from the management, the union (if any), the employees from the supervisory rank, and from the rank and file employees. In an educational or training institution, the committee shall be composed of at least one representative from the administration, the trainers, teachers, instructors, professors or coaches and students or trainees, as the case may be.",
    punishment: null,
    keywords: ["CODI", "composition", "management", "union", "students"],
    applicable_to: ["employers", "educational institutions"],
    category: "anti_sexual_harassment_act",
    relevance_score: 0.9
  },
  {
    policy_id: "POL-RA7877-004",
    title: "RA 7877 – Solidary Liability of Employer/Head of Office",
    source: "RA 7877 (Anti-Sexual Harassment Act of 1995)",
    section: "Sec. 5",
    content: "The employer or head of office, educational or training institution shall be solidarily liable for damages arising from the acts of sexual harassment committed in the employment, education or training environment if the employer or head of office, educational or training institution is informed of such acts by the offended party and no immediate action is taken thereon.",
    punishment: "Solidary liability for damages.",
    keywords: ["solidary liability", "damages", "failure to act"],
    applicable_to: ["employers", "heads of offices", "educational institutions"],
    category: "anti_sexual_harassment_act",
    relevance_score: 0.9
  },
  {
    policy_id: "POL-RA7877-005",
    title: "RA 7877 – Independent Action for Damages",
    source: "RA 7877 (Anti-Sexual Harassment Act of 1995)",
    section: "Sec. 6",
    content: "Nothing in this Act shall preclude the victim of work, education or training‑related sexual harassment from instituting a separate and independent action for damages and other affirmative relief.",
    punishment: null,
    keywords: ["independent action", "damages", "civil action"],
    applicable_to: ["victims"],
    category: "anti_sexual_harassment_act",
    relevance_score: 0.8
  },
  {
    policy_id: "POL-RA7877-006",
    title: "RA 7877 – Penalties",
    source: "RA 7877 (Anti-Sexual Harassment Act of 1995)",
    section: "Sec. 7",
    content: "Any person who violates the provisions of this Act shall, upon conviction, be penalized.",
    punishment: "Imprisonment of not less than one month nor more than six months, or a fine of not less than PHP 10,000 nor more than PHP 20,000, or both such fine and imprisonment at the discretion of the court. Any action arising from the violation shall prescribe in three years.",
    keywords: ["penalties", "imprisonment", "fine", "prescription"],
    applicable_to: ["all persons"],
    category: "anti_sexual_harassment_act_penalties",
    relevance_score: 0.9
  },
  {
    policy_id: "POL-RA7877-007",
    title: "RA 7877 – Separability, Repealing, Effectivity",
    source: "RA 7877 (Anti-Sexual Harassment Act of 1995)",
    section: "Secs. 8‑10",
    content: "If any portion is declared void, the remainder shall not be affected. All laws inconsistent are repealed. The Act takes effect fifteen days after publication in at least two national newspapers.",
    punishment: null,
    keywords: ["separability", "repeal", "effectivity"],
    applicable_to: ["all persons"],
    category: "anti_sexual_harassment_act",
    relevance_score: 0.5
  },
  {
    policy_id: "POL-RA7877-008",
    title: "CSC MC No. 19 – Policy on Sexual Harassment in the Workplace",
    source: "CSC MC No. 19, s. 1994",
    section: "Resolution No. 94‑2854",
    content: "The Civil Service Commission adopts a policy on sexual harassment in the workplace, recognizing sexual harassment as a violation of human rights, morale, and efficiency. The policy covers all government officials and employees, and includes applicants for employment. Sexual harassment is defined as one or a series of incidents involving unwelcome sexual advances, requests for sexual favours, or other verbal or physical conduct of a sexual nature made directly, indirectly, or impliedly when: (1) it might reasonably cause insecurity, discomfort, offense, or humiliation; (2) submission is a condition of employment; (3) submission/rejection is used as a basis for employment decisions; (4) it interferes with work performance or creates a hostile environment.",
    punishment: "Grave Misconduct, Conduct Prejudicial to the Best Interest of the Service, or Simple Misconduct, with penalties up to dismissal.",
    keywords: ["CSC", "policy", "workplace", "definition", "hostile environment"],
    applicable_to: ["government officials", "employees"],
    category: "civil_service_harassment",
    relevance_score: 0.9
  },
  {
    policy_id: "POL-RA7877-009",
    title: "CSC MC No. 19 – Responsibilities of Heads of Agencies",
    source: "CSC MC No. 19, s. 1994",
    section: "Sec. 4",
    content: "Heads of agencies are responsible for: (1) informing officials and employees of the policy; (2) investigating every formal written complaint and imposing strict disciplinary measures; (3) providing advice, support, and assistance to employees subjected to sexual harassment; (4) appointing advisors and providing training; (5) designating an officer for investigation and hearing; (6) maintaining confidentiality; (7) maintaining records.",
    punishment: null,
    keywords: ["head of agency", "duties", "investigation", "confidentiality"],
    applicable_to: ["heads of government agencies"],
    category: "civil_service_harassment",
    relevance_score: 0.9
  },
  {
    policy_id: "POL-RA7877-010",
    title: "CSC Resolution No. 956161 – Scope and Definition",
    source: "CSC Resolution No. 956161",
    section: "Rule I‑III",
    content: "These rules apply to all officials and employees in the CSC. The Commission exercises exclusive jurisdiction over acts constituting sexual harassment. Sexual harassment is defined as a form of misconduct involving unwelcome sexual advances, requests for sexual favours, or other verbal or physical behaviour of a sexual nature, made directly, indirectly or impliedly under specific instances.",
    punishment: null,
    keywords: ["CSC", "implementing rules", "jurisdiction", "definition"],
    applicable_to: ["CSC officials and employees"],
    category: "civil_service_harassment",
    relevance_score: 0.8
  },
  {
    policy_id: "POL-RA7877-011",
    title: "CSC Resolution No. 956161 – Specific Acts Constituting Sexual Harassment",
    source: "CSC Resolution No. 956161",
    section: "Rule IV",
    content: "The following acts constitute employment or work‑related sexual harassment: (a) demand, request, or requirement for sexual favor as a condition for hiring, employment, re‑employment, continued employment, favorable compensation, terms, conditions, promotion, or privileges; (b) demand against one whose training is entrusted to the offender; (c) refusal of demand leading to limitation, segregation, or discrimination; (d) acts that impair rights under labor laws; (e) acts that result in intimidating, hostile, or offensive environment. These acts may occur in the office, anywhere as a result of work responsibilities, at office‑related social functions, during official travel, at conferences, over telephone, email, etc.",
    punishment: null,
    keywords: ["specific acts", "employment", "conditions", "hostile environment"],
    applicable_to: ["government officials", "employees"],
    category: "civil_service_harassment",
    relevance_score: 0.9
  },
  {
    policy_id: "POL-RA7877-012",
    title: "CSC Resolution No. 956161 – Forms of Sexual Harassment",
    source: "CSC Resolution No. 956161",
    section: "Rule V",
    content: "Sexual harassment may take the following forms: (a) Physical – physical contact or malicious touching, overt sexual advances, unwelcome or improper gesture of a sexual nature, suggestive expression or lewd insinuation; (b) Verbal – requests or demands for sexual favors or lurid remarks; (c) Use of objects, pictures, letters, or written notes with bold persuasive sexual underpinnings that create a hostile, offensive, or intimidating environment.",
    punishment: null,
    keywords: ["forms", "physical", "verbal", "objects", "hostile environment"],
    applicable_to: ["government officials", "employees"],
    category: "civil_service_harassment",
    relevance_score: 0.9
  },
  {
    policy_id: "POL-RA7877-013",
    title: "CSC Resolution No. 956161 – Persons Liable",
    source: "CSC Resolution No. 956161",
    section: "Rule VI",
    content: "Any official having authority, influence, or moral ascendancy over another, or any employee, regardless of sex, are liable. Also liable are those who direct or induce another to commit sexual harassment (principal by induction) or cooperate in its commission without which it would not have been committed (principal by indispensable cooperation).",
    punishment: null,
    keywords: ["liability", "moral ascendancy", "induction", "cooperation"],
    applicable_to: ["government officials", "employees"],
    category: "civil_service_harassment",
    relevance_score: 0.85
  },
  {
    policy_id: "POL-RA7877-014",
    title: "CSC Resolution No. 956161 – Committee on Decorum and Investigation (CODI) in CSC",
    source: "CSC Resolution No. 956161",
    section: "Rule VII‑VIII",
    content: "The CSC and each Regional Office shall create a Committee on Decorum and Investigation. The Committee receives complaints, files formal charges, investigates, submits findings and recommendations. It also conducts meetings to increase understanding and prevent incidents. The composition includes a Director (Chair), the CSC Focal Point on Women and Development, a representative of the Employee Association, a second level employee, and a first level employee.",
    punishment: null,
    keywords: ["CODI", "composition", "investigation", "prevention"],
    applicable_to: ["CSC", "regional offices"],
    category: "civil_service_harassment",
    relevance_score: 0.8
  },
  {
    policy_id: "POL-RA7877-015",
    title: "CSC Resolution No. 956161 – Classification of Offenses (Grave, Less Grave, Light)",
    source: "CSC Resolution No. 956161",
    section: "Annex",
    content: "Grave offenses: unwanted touching of private parts, sexual assault, acts committed by superior with moral ascendancy. Less grave offenses: requesting dates or sexual favors in exchange for employment/promotion/benefits; pinching not falling under grave; unnecessary touching/brushing; derogatory remarks; verbal abuse/threats. Light offenses: persistently telling sexist/smutty jokes; leering/ogling; voyeurism; display of offensive pictures; unwelcome inquiries about sex life; unwelcome flirtation; offensive hand/body gestures; persistent unwanted contact after relationship ends.",
    punishment: "Grave – dismissal; Less grave – suspension 1 month 1 day to 6 months (or dismissal for second); Light – reprimand, suspension 1‑30 days (or dismissal for third).",
    keywords: ["classification", "grave", "less grave", "light", "penalties"],
    applicable_to: ["government officials", "employees"],
    category: "civil_service_harassment",
    relevance_score: 0.95
  },
  {
    policy_id: "POL-RA7877-016",
    title: "CSC Resolution No. 956161 – Procedures in Disposition of Sexual Harassment Cases",
    source: "CSC Resolution No. 956161",
    section: "Rule IX",
    content: "Complaints must be under oath. No action on anonymous complaints. The head of office transmits the complaint to the CODI within 5 days. Preliminary investigation is conducted; the respondent submits counter‑affidavits. If a prima facie case is found, a formal charge is issued. The formal investigation shall be completed within 30 days from service of the formal charge. Failure to file answer waives the right. The Committee submits a report to the Commission for final decision.",
    punishment: null,
    keywords: ["procedure", "complaint", "investigation", "formal charge", "answer"],
    applicable_to: ["government agencies", "CODI"],
    category: "civil_service_harassment",
    relevance_score: 0.7
  },
  {
    policy_id: "POL-RA7877-017",
    title: "DOLE Administrative Order No. 68 – Policy Against Sexual Harassment",
    source: "DOLE Administrative Order No. 68, s. 1992",
    section: "Secs. 1‑2",
    content: "The Department of Labor and Employment shall not tolerate sexual harassment committed by DOLE officials, employees, applicants for employment or any person transacting official business with DOLE. Sexual harassment is defined as any unwanted or uninvited sexual attention or advances, requests for sexual favors, or other verbal or physical conduct of a sexual nature, when: (1) committed to take advantage of weakness, vulnerability, status, or professional/social/economic standing; (2) explicitly or implicitly imposed as a condition for securing employment, advancement, promotion, or preferential treatment; (3) adversely interfering with official's or employee's performance; (4) bound to create a hostile, offensive, intimidating, or uncomfortable work environment.",
    punishment: "Classified as a grave offense under DOLE Manual on Disposition of Administrative Cases.",
    keywords: ["DOLE", "policy", "workplace", "definition", "grave offense"],
    applicable_to: ["DOLE officials", "employees", "applicants", "clients"],
    category: "civil_service_harassment",
    relevance_score: 0.85
  },
  {
    policy_id: "POL-RA7877-018",
    title: "DOLE – Fact‑Finding Committee and Procedure",
    source: "DOLE Administrative Order No. 68, s. 1992",
    section: "Secs. 3‑5",
    content: "A Special Fact‑Finding Committee is created to receive and investigate/hear sexual harassment complaints and submit reports/recommendations to the Secretary. The Committee is composed of the DOLE Resident Ombudsperson (Chair), Chairperson of DOLE PDPW Focal Point (Co‑Chair), Assistant Secretary for Management Services, Director of Human Resource Development Service, Director of Legal Service, President of DOLE Employees Union (ad hoc), and Resident Ombudsperson of the Agency Concerned (ad hoc). The Legal Service acts as Secretariat. The Secretary shall promulgate rules and regulations implementing the Order.",
    punishment: null,
    keywords: ["fact-finding committee", "composition", "investigation", "secretariat"],
    applicable_to: ["DOLE"],
    category: "civil_service_harassment",
    relevance_score: 0.7
  },
  {
    policy_id: "POL-RA7877-019",
    title: "DOLE – Awareness Raising Campaign",
    source: "DOLE Administrative Order No. 68, s. 1992",
    section: "Sec. 6",
    content: "Concerned agencies shall undertake information dissemination campaigns to raise awareness on the policy against sexual harassment and to prevent incidence of the same.",
    punishment: null,
    keywords: ["awareness", "campaign", "information dissemination", "prevention"],
    applicable_to: ["DOLE agencies"],
    category: "civil_service_harassment",
    relevance_score: 0.6
  }
];

const ra9262 = [
  {
    policy_id: "POL-RA9262-001",
    title: "VAWC – Definition and Scope",
    source: "RA 9262 (VAWC Act of 2004) – Summary",
    section: "Overview",
    content: "RA 9262, the Anti‑Violence Against Women and Their Children Act of 2004, seeks to address violence against women and their children by intimate partners (husband, ex‑husband, live‑in partner, boyfriend, dating partner, etc.). VAWC refers to any act or series of acts committed by any person against a woman who is his wife, former wife, or against a woman with whom he has or had a sexual or dating relationship, or with whom he has a common child, or against her child, which result in or likely result in physical, sexual, psychological harm or suffering, or economic abuse, including threats, battery, assault, coercion, harassment, or arbitrary deprivation of liberty.",
    punishment: null,
    keywords: ["VAWC", "definition", "intimate partner", "violence"],
    applicable_to: ["women", "children"],
    category: "vawc_act",
    relevance_score: 1.0
  },
  {
    policy_id: "POL-RA9262-002",
    title: "VAWC – Forms of Violence",
    source: "RA 9262 (VAWC Act of 2004) – Summary",
    section: "Forms",
    content: "Physical violence: acts that include bodily or physical harm. Sexual violence: acts sexual in nature, including rape, sexual harassment, acts of lasciviousness, treating as sex object, demeaning remarks, attacking sexual parts, forcing to watch obscene materials, forcing sexual activity by threat, prostituting. Psychological violence: acts causing mental/emotional suffering, including intimidation, harassment, stalking, damage to property, public ridicule, repeated verbal abuse, marital infidelity, forcing witness to abuse. Economic abuse: acts making a woman financially dependent, including withdrawal of support, preventing employment, controlling resources, destroying property.",
    punishment: null,
    keywords: ["physical violence", "sexual violence", "psychological violence", "economic abuse"],
    applicable_to: ["women", "children"],
    category: "vawc_act",
    relevance_score: 0.9
  },
  {
    policy_id: "POL-RA9262-003",
    title: "VAWC – Who May Apply for Protection Orders",
    source: "RA 9262 (VAWC Act of 2004) – Summary",
    section: "Protection Orders",
    content: "The following may apply for a protection order: (a) the offended party; (b) parents or guardians; (c) ascendants, descendants, or collateral relatives within the fourth civil degree; (d) officers or social workers of DSWD or LGUs; (e) police officers (preferably from women and children's desk); (f) Punong Barangay or Barangay Kagawad; (g) lawyers, counselors, therapists, health care providers of the petitioner; (h) at least two concerned citizens of the city/municipality where VAWC happened with personal knowledge.",
    punishment: null,
    keywords: ["protection order", "applicants", "BPO", "TPO", "PPO"],
    applicable_to: ["victims", "relatives", "social workers", "police"],
    category: "vawc_act",
    relevance_score: 0.9
  },
  {
    policy_id: "POL-RA9262-004",
    title: "VAWC – Kinds of Protection Orders",
    source: "RA 9262 (VAWC Act of 2004) – Summary",
    section: "Protection Orders",
    content: "There are three kinds of protection orders: Barangay Protection Order (BPO) – issued by the barangay to prevent further violence; Temporary Protection Order (TPO) – issued by the court and effective until a permanent order is issued; Permanent Protection Order (PPO) – issued by the court after notice and hearing.",
    punishment: "Violation of a protection order is punishable by imprisonment and fine.",
    keywords: ["BPO", "TPO", "PPO", "barangay", "court"],
    applicable_to: ["victims", "offenders"],
    category: "vawc_act",
    relevance_score: 0.9
  },
  {
    policy_id: "POL-RA9262-005",
    title: "VAWC – Where to File and Who May File",
    source: "RA 9262 (VAWC Act of 2004) – Summary",
    section: "Filing",
    content: "Cases may be filed in the Regional Trial Court designated as Family Court of the place where the crime was committed. Because VAWC is considered a public crime, any citizen having personal knowledge of the circumstances may file a complaint.",
    punishment: null,
    keywords: ["venue", "family court", "public crime", "any citizen"],
    applicable_to: ["all citizens", "victims"],
    category: "vawc_act",
    relevance_score: 0.8
  },
  {
    policy_id: "POL-RA9262-006",
    title: "VAWC – Penalties",
    source: "RA 9262 (VAWC Act of 2004) – Summary",
    section: "Penalties",
    content: "Offenders proven guilty shall be penalized.",
    punishment: "Imprisonment ranging from 1 month and 1 day to 20 years; payment of PHP 100,000 to PHP 300,000 in damages; mandatory psychological counseling or psychiatric treatment.",
    keywords: ["penalties", "imprisonment", "damages", "counseling"],
    applicable_to: ["offenders"],
    category: "vawc_act_penalties",
    relevance_score: 0.9
  },
  {
    policy_id: "POL-RA9262-007",
    title: "VAWC – Battered Woman Syndrome (BWS)",
    source: "RA 9262 (VAWC Act of 2004) – Summary",
    section: "BWS",
    content: "RA 9262 acknowledges Battered Woman Syndrome (BWS) as a pattern of psychological and behavioral symptoms found in battered women as a result of a long history of abuse. Any victim who suffers from BWS should be diagnosed by a psychiatric expert or clinical psychologist. This may help the victim obtain a just decision. The law does not allow the offender to have custody of minor children; their care is entrusted to the woman even if she is found to have BWS.",
    punishment: null,
    keywords: ["battered woman syndrome", "BWS", "diagnosis", "custody"],
    applicable_to: ["victims", "courts"],
    category: "vawc_act",
    relevance_score: 0.85
  },
  {
    policy_id: "POL-RA9262-008",
    title: "VAWC – Assistance and Contact Points",
    source: "RA 9262 (VAWC Act of 2004) – Summary",
    section: "Assistance",
    content: "Victims can seek help from: Barangay VAW Desk; Provincial/City/Municipal Social Welfare and Development Office; DSWD Community‑Based Services Section; PNP Women and Children Protection Center; NBI Anti‑Violence Against Women and Children Desk; DOJ Public Attorney's Office; UP‑PGH Women's Desk; DOH Hospitals Women and Children Protection Unit; Women's Crisis Center.",
    punishment: null,
    keywords: ["assistance", "hotline", "VAW desk", "WCPC", "DSWD"],
    applicable_to: ["victims"],
    category: "vawc_act",
    relevance_score: 0.7
  }
];

const raccs = [
  {
    policy_id: "POL-RACCS-001",
    title: "Title and Applicability",
    source: "2017 RACCS",
    section: "Rule 1, Secs. 1‑2",
    content: "These Rules shall be known and cited as the 2017 Rules on Administrative Cases in the Civil Service (2017 RACCS). They apply to all disciplinary and non‑disciplinary administrative cases or matters brought before the CSC, its regional/field offices, agencies of the national government, local government units, state universities and colleges, and government‑owned or controlled corporations with original charters, except as may be provided by law.",
    punishment: null,
    keywords: ["title", "applicability", "coverage"],
    applicable_to: ["government agencies", "CSC"],
    category: "rac_civil_service",
    relevance_score: 0.6
  },
  {
    policy_id: "POL-RACCS-002",
    title: "Construction and Definition of Terms",
    source: "2017 RACCS",
    section: "Rule 1, Secs. 3‑4",
    content: "These Rules shall be liberally construed to promote just, speedy, and inexpensive disposition of cases. Administrative investigations are conducted without strict recourse to technical rules of procedure and evidence. Key terms defined: Agency, Appointing Authority, Back Wages, Civil Service, CSC Field/Regional Offices, Commission, Department, Developmental Interventions, Disciplining Authority, Employee, Fixer, Forum Shopping, HR Action, Official, Party Adversely Affected, Person Complained Of, Prima Facie Case, Probationary Employee, Protest, Psychological Interventions, Qualified Next‑in‑Rank, Respondent, Sexual Harassment, Show‑Cause Order.",
    punishment: null,
    keywords: ["construction", "definitions", "liberal construction"],
    applicable_to: ["all parties"],
    category: "rac_civil_service",
    relevance_score: 0.7
  },
  {
    policy_id: "POL-RACCS-003",
    title: "Definition of Sexual Harassment",
    source: "2017 RACCS",
    section: "Rule 1, Sec. 4(aa)",
    content: "Sexual harassment refers to an act, or a series of acts, involving any unwelcome sexual advance, request or demand for a sexual favor, or other verbal or physical behavior of a sexual nature, committed by a government employee or official in a work‑related, training or education related environment of the person complained of.",
    punishment: null,
    keywords: ["sexual harassment", "definition", "civil service"],
    applicable_to: ["government employees", "officials"],
    category: "rac_civil_service",
    relevance_score: 0.9
  },
  {
    policy_id: "POL-RACCS-004",
    title: "Jurisdiction of the CSC",
    source: "2017 RACCS",
    section: "Rule 2, Secs. 5‑9",
    content: "The CSC hears and decides administrative cases directly or on appeal. It has jurisdiction over decisions of CSC ROs brought on petition for review; complaints against CSC officials and employees; complaints against non‑presidential appointees; appeals from decisions imposing penalties exceeding 30 days suspension or fine; cases where due process was violated; appeals from orders of preventive suspension; and non‑disciplinary matters like human resource actions, requests for removal of penalties, etc. CSC ROs have original jurisdiction over cases where acts were committed within their region, including fraudulent acquisition of eligibility. Disciplining authorities have original concurrent jurisdiction over their own officials and employees; decisions imposing ≤30 days suspension or fine are final, while dismissal is executory only after confirmation.",
    punishment: null,
    keywords: ["jurisdiction", "CSC", "regional offices", "disciplining authority"],
    applicable_to: ["CSC", "government agencies"],
    category: "rac_civil_service",
    relevance_score: 0.8
  },
  {
    policy_id: "POL-RACCS-005",
    title: "Complaint – Who May Initiate and Requisites",
    source: "2017 RACCS",
    section: "Rule 3, Secs. 10‑13",
    content: "Administrative proceedings may be initiated by the disciplining authority motu proprio or upon complaint of any person. The complaint must be in writing, subscribed and sworn to by the complainant, and contain: full name and address of complainant and person complained of; position and office; narration of facts; certified true copies of documentary evidence and affidavits; certification of non‑forum shopping. Anonymous complaints are not entertained unless the act is of public knowledge or can be verified by documentary or direct evidence.",
    punishment: null,
    keywords: ["complaint", "requisites", "sworn", "non-forum shopping", "anonymous complaint"],
    applicable_to: ["complainants"],
    category: "rac_civil_service",
    relevance_score: 0.7
  },
  {
    policy_id: "POL-RACCS-006",
    title: "CODI Creation and Composition",
    source: "2017 RACCS",
    section: "Rule 3, Secs. 14‑15",
    content: "All national/local government agencies, SUCs, and GOCCs with original charters must create a Committee on Decorum and Investigation (CODI). In a work‑related environment, CODI is composed of at least one representative each from management, the accredited union (if any), second level employees, and first level employees. In an educational/training institution, representatives from administration, teaching/non‑teaching staff, and students/trainees. Failure to create a CODI is Neglect of Duty. If a complaint is filed with the CSC, it is remanded to the agency, but CSC may take cognizance if: agency has no CODI; disciplining authority is the subject; subject is a CODI member; or unreasonable delay in investigation.",
    punishment: "Neglect of Duty for head of office failing to create CODI.",
    keywords: ["CODI", "composition", "neglect of duty", "remand", "jurisdiction"],
    applicable_to: ["government agencies", "SUCs", "GOCCs"],
    category: "rac_civil_service",
    relevance_score: 0.9
  },
  {
    policy_id: "POL-RACCS-007",
    title: "Withdrawal of Complaint and Action on Complaint",
    source: "2017 RACCS",
    section: "Rule 3, Secs. 16‑17",
    content: "Withdrawal of the complaint does not result in its outright dismissal or discharge from administrative liability. Upon receipt of a sufficient complaint, the disciplining authority conducts a preliminary investigation to determine prima facie case. In sexual harassment cases, the CODI receives complaints, investigates, submits findings and recommendation, and leads in discussions to increase understanding and prevent incidents.",
    punishment: null,
    keywords: ["withdrawal", "preliminary investigation", "CODI functions"],
    applicable_to: ["disciplining authorities", "CODI"],
    category: "rac_civil_service",
    relevance_score: 0.7
  },
  {
    policy_id: "POL-RACCS-008",
    title: "Formal Charge and Notice of Charge",
    source: "2017 RACCS",
    section: "Rule 5, Secs. 23‑25",
    content: "After a finding of prima facie case, the disciplining authority shall formally charge the respondent. The formal charge must specify the charge, state material facts, direct the respondent to answer under oath within 3‑10 days, advise whether a formal investigation is demanded, and inform of the right to counsel. A notice of charge (when complaint initiated by another) includes the charge, directive to answer, and notice of rights. Prohibited pleadings: motions to dismiss, motions for extension, etc.; these are noted without action.",
    punishment: null,
    keywords: ["formal charge", "notice of charge", "answer", "prohibited pleadings"],
    applicable_to: ["disciplining authorities", "respondents"],
    category: "rac_civil_service",
    relevance_score: 0.75
  },
  {
    policy_id: "POL-RACCS-009",
    title: "Answer",
    source: "2017 RACCS",
    section: "Rule 6, Secs. 26‑27",
    content: "The answer must be in writing, under oath, specific, and contain material facts, applicable laws, documentary evidence, and sworn statements of witnesses. If the disciplining authority finds the answer satisfactory, the case is dismissed. Failure to file an answer within the period waives the right, and the case is decided based on available records.",
    punishment: null,
    keywords: ["answer", "oath", "waiver", "dismissal"],
    applicable_to: ["respondents"],
    category: "rac_civil_service",
    relevance_score: 0.7
  },
  {
    policy_id: "POL-RACCS-010",
    title: "Preventive Suspension",
    source: "2017 RACCS",
    section: "Rule 7, Secs. 28‑33",
    content: "Preventive suspension is not a penalty; it is a precautionary measure to remove the respondent from the scene during investigation. It may be issued upon issuance of formal charge if the charge involves dishonesty, oppression, grave misconduct, neglect, or offenses punishable by dismissal, and the respondent is in a position to exert undue influence or pressure on witnesses or tamper with evidence. Maximum duration: 90 days for national agencies/GOCCs/SUCs, 60 days for LGUs. If the case is not decided within the period, the respondent is automatically reinstated unless the delay is caused by the respondent. Back wages may be paid if the suspension order is void or if the respondent is exonerated.",
    punishment: null,
    keywords: ["preventive suspension", "duration", "reinstatement", "back wages"],
    applicable_to: ["disciplining authorities", "respondents"],
    category: "rac_civil_service",
    relevance_score: 0.85
  },
  {
    policy_id: "POL-RACCS-011",
    title: "Formal Investigation",
    source: "2017 RACCS",
    section: "Rule 8, Secs. 34‑47",
    content: "A formal investigation is conducted when the merits cannot be decided without it or when demanded by the respondent. It must be finished within 30 days from issuance of the formal charge. Pre‑hearing conference is held to stipulate facts, simplify issues, mark evidence, and set hearing dates. The hearing is continuous; each party may have one postponement. Failure of respondent to appear waives the right to present evidence. The hearing officer may issue subpoenas. Within 15 days after conclusion, the hearing officer submits a report with findings and recommendation to the disciplining authority.",
    punishment: null,
    keywords: ["formal investigation", "pre-hearing", "subpoena", "report"],
    applicable_to: ["hearing officers", "disciplining authorities", "respondents"],
    category: "rac_civil_service",
    relevance_score: 0.7
  },
  {
    policy_id: "POL-RACCS-012",
    title: "Decision",
    source: "2017 RACCS",
    section: "Rule 9, Secs. 48‑49",
    content: "The disciplining authority decides the case within 30 days from receipt of the investigation report. Decisions imposing reprimand, suspension of 30 days or less, or fine not exceeding 30 days salary are final and executory unless a motion for reconsideration is timely filed. Decisions imposing longer suspension or greater fines are final after lapse of appeal period without appeal. Dismissal penalties are executory only after confirmation.",
    punishment: null,
    keywords: ["decision", "finality", "executory", "dismissal confirmation"],
    applicable_to: ["disciplining authorities", "respondents"],
    category: "rac_civil_service",
    relevance_score: 0.8
  },
  {
    policy_id: "POL-RACCS-013",
    title: "Classification of Offenses",
    source: "2017 RACCS",
    section: "Rule 10, Sec. 50",
    content: "Offenses are classified as grave, less grave, or light. Grave offenses: serious dishonesty, gross neglect, grave misconduct, notorious undesirability, conviction of crime involving moral turpitude, falsification, immoral habits, graft‑related acts, nepotism, disloyalty. Grave offenses punishable by dismissal; some grave offenses punishable by suspension (6 months 1 day to 1 year) or dismissal for second offense. Less grave offenses: neglect of duty, misconduct, discourtesy, insubordination, habitual drunkenness, discrimination, failure to disclose assets, etc., punishable by suspension (1 month 1 day to 6 months) or dismissal for second offense. Light offenses: discourtesy, improper solicitations, rule violations, habitual tardiness, gambling, refusal of overtime, willful failure to pay debts, failure to act promptly, etc., punishable by reprimand, suspension (1‑30 days), or dismissal for third offense.",
    punishment: "As described in content.",
    keywords: ["classification", "grave", "less grave", "light", "penalties"],
    applicable_to: ["government employees", "officials"],
    category: "rac_civil_service",
    relevance_score: 0.85
  },
  {
    policy_id: "POL-RACCS-014",
    title: "Penalties for Sexual Harassment",
    source: "2017 RACCS",
    section: "Rule 10, Sec. 51",
    content: "Sexual harassment is classified into grave, less grave, or light based on nature and gravity. The classification follows the examples and contexts provided in CSC Resolution No. 956161. Persons liable include direct participants, those inducing, directing, or cooperating in the acts.",
    punishment: "Light – reprimand, suspension 1‑30 days, or dismissal for third offense; less grave – suspension 1 month 1 day to 6 months or dismissal for second; grave – dismissal.",
    keywords: ["sexual harassment", "penalties", "dismissal", "suspension"],
    applicable_to: ["government employees", "officials"],
    category: "rac_civil_service",
    relevance_score: 0.9
  },
  {
    policy_id: "POL-RACCS-015",
    title: "Mitigating and Aggravating Circumstances",
    source: "2017 RACCS",
    section: "Rule 10, Sec. 53",
    content: "Mitigating circumstances include: voluntary surrender, first offense, length of service, good faith, immediate rectification, physical illness, and other analogous circumstances. Aggravating circumstances include: taking advantage of position, use of confidential information, recidivism, commission in the presence of subordinates, and other analogous circumstances.",
    punishment: "Mitigating circumstances may reduce penalty; aggravating may increase.",
    keywords: ["mitigating", "aggravating", "penalty adjustment"],
    applicable_to: ["disciplining authorities"],
    category: "rac_civil_service",
    relevance_score: 0.7
  },
  {
    policy_id: "POL-RACCS-016",
    title: "Motion for Reconsideration",
    source: "2017 RACCS",
    section: "Rule 12, Secs. 61‑65",
    content: "An adversely affected party may file a motion for reconsideration within 15 days from receipt. Grounds: new evidence, decision not supported by evidence, or errors prejudicial to movant. Only one motion is allowed; filing stays execution of the decision.",
    punishment: null,
    keywords: ["motion for reconsideration", "grounds", "stay"],
    applicable_to: ["parties"],
    category: "rac_civil_service",
    relevance_score: 0.65
  },
  {
    policy_id: "POL-RACCS-017",
    title: "Appeal in Disciplinary Cases",
    source: "2017 RACCS",
    section: "Rule 13, Secs. 66‑73",
    content: "Appeal is allowed from decisions imposing penalties over 30 days suspension or fine exceeding 30 days salary. Appeal must be filed within 15 days from receipt. An appeal generally does not stop execution except when the penalty is dismissal (executory only after confirmation). The Commission may review decisions of CSC Regional Offices via petition for review.",
    punishment: null,
    keywords: ["appeal", "petition for review", "execution", "dismissal"],
    applicable_to: ["parties"],
    category: "rac_civil_service",
    relevance_score: 0.7
  },
  {
    policy_id: "POL-RACCS-018",
    title: "Back Wages",
    source: "2017 RACCS",
    section: "Rule 14, Secs. 74‑77",
    content: "An illegally dismissed or suspended employee who is exonerated or reprimanded and reinstated is entitled to back wages and other benefits. Back wages include salaries from dismissal to reinstatement, RATA, PERA/ACA, restored leave credits, loyalty award, anniversary bonus, 13th/14th month pay, cash gift, uniform allowance, performance‑based bonus. Computation is based on salary grade at dismissal plus increases.",
    punishment: null,
    keywords: ["back wages", "reinstatement", "benefits", "computation"],
    applicable_to: ["illegally dismissed employees"],
    category: "rac_civil_service",
    relevance_score: 0.8
  },
  {
    policy_id: "POL-RACCS-019",
    title: "Dropping from Rolls – AWOL",
    source: "2017 RACCS",
    section: "Rule 20, Sec. 107(a)",
    content: "An official or employee continuously absent without official leave (AWOL) for at least 30 working days may be dropped from the rolls without prior notice. The employee has 15 days to appeal from receipt of the notice. If absences are less than 30 days but a pattern shows circumvention (e.g., three times in a semester with substantial absences), dropping may also be justified.",
    punishment: "Separation from service (non‑disciplinary, no forfeiture of benefits).",
    keywords: ["AWOL", "dropping from rolls", "separation", "appeal"],
    applicable_to: ["government employees"],
    category: "rac_civil_service",
    relevance_score: 0.8
  },
  {
    policy_id: "POL-RACCS-020",
    title: "Dropping from Rolls – Unsatisfactory Performance",
    source: "2017 RACCS",
    section: "Rule 20, Sec. 107(b)",
    content: "An employee with Unsatisfactory rating for one period or poor performance within first 3 months shall be given developmental intervention. If after intervention the employee still gets Poor or Unsatisfactory rating in the succeeding period, the employee may be dropped after due notice. Two consecutive Unsatisfactory ratings may lead to dropping.",
    punishment: "Separation from service (non‑disciplinary).",
    keywords: ["unsatisfactory performance", "developmental intervention", "dropping from rolls"],
    applicable_to: ["government employees"],
    category: "rac_civil_service",
    relevance_score: 0.8
  },
  {
    policy_id: "POL-RACCS-021",
    title: "Dropping from Rolls – Physical or Mental Unfitness",
    source: "2017 RACCS",
    section: "Rule 20, Sec. 107(c)‑(d)",
    content: "An employee continuously absent for more than one year due to illness, or intermittently absent for at least 260 working days in a 24‑month period, may be declared physically unfit and dropped. For mental disorder, if after human resource and psychological interventions abnormal behavior continues as confirmed by a licensed psychiatrist, the employee may be dropped. If the employee refuses interventions, dropping may be based on a psychiatrist’s report.",
    punishment: "Separation from service (non‑disciplinary).",
    keywords: ["physical unfitness", "mental disorder", "dropping from rolls", "psychiatrist"],
    applicable_to: ["government employees"],
    category: "rac_civil_service",
    relevance_score: 0.8
  },
  {
    policy_id: "POL-RACCS-022",
    title: "Settlement in Administrative Cases",
    source: "2017 RACCS",
    section: "Rule 11, Secs. 59‑60",
    content: "Settlement is allowed for light offenses if purely personal and with no apparent injury to government. It is not allowed for second offense of the same act. The person complained of may move for settlement anytime before formal charge. If a compromise agreement is executed, it is binding unless proven duress or fraud. If settlement fails, proceedings continue.",
    punishment: null,
    keywords: ["settlement", "compromise", "light offense"],
    applicable_to: ["respondents", "disciplining authorities"],
    category: "rac_civil_service",
    relevance_score: 0.6
  },
  {
    policy_id: "POL-RACCS-023",
    title: "Removal of Administrative Penalties or Disabilities",
    source: "2017 RACCS",
    section: "Rule 15, Secs. 78‑81",
    content: "In meritorious cases, upon recommendation of the CSC, the President may commute or remove administrative penalties or disabilities. A dismissed official may petition for a favorable recommendation after at least three years from finality of decision, demonstrating moral reformation, restitution if applicable, and other requirements. If granted, the privilege to be employed in government service is restored, unless the President orders otherwise.",
    punishment: null,
    keywords: ["removal of penalties", "rehabilitation", "re-employment"],
    applicable_to: ["dismissed employees"],
    category: "rac_civil_service",
    relevance_score: 0.7
  },
  {
    policy_id: "POL-RACCS-024",
    title: "Contempt",
    source: "2017 RACCS",
    section: "Rule 16, Secs. 82‑85",
    content: "Any person found guilty of disobedience or resistance to a lawful writ, process, order, decision, or subpoena of the Commission may be punished for indirect contempt. Proceedings may be initiated motu proprio or by motion. If found guilty, penalty is a fine of PHP 1,000 per day for every act and/or suspension for 1 month up to 6 months.",
    punishment: "Fine up to PHP 1,000/day and/or suspension 1‑6 months.",
    keywords: ["contempt", "indirect contempt", "fine", "suspension"],
    applicable_to: ["all persons"],
    category: "rac_civil_service",
    relevance_score: 0.6
  }
];